version: '3.7'
services:
  rdocs-app:
    container_name: rdocs-app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=rdocs
      - DATABASE_PORT=3306
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - gateway
  db:
    container_name: mysql-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=rdoc
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=rdocs
    networks:
      - gateway
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - gateway
networks:
  gateway: {}