version: "2"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: rdoc
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: rdocs
  redis:
    image: redis
    ports:
      - "6379:6379"
